GET {{server}}/login


###
POST {{server}}/users
Content-Type: application/json

{
  "username": "admin",
  "fullname": "Test Persson",
  "password": "3windisnq2r1"
}

###
GET {{server}}/users

###
POST {{server}}/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=3windisnq2r1

###
GET {{server}}/login
